### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by hhirtz** [rsmpi/rsmpi#109]
The rsmpi project hasn't received any commit to master since march, and only 1 pull request has been opened in 2021. The last release is from 4 years ago.

Are there people interested in using rsmpi? Is there any alternative? If not, can we organize for a fork or something (even through it'd be better to keep the crate name and the repo)

In any case, thanks to the contributors who have already put a lot work into this.

**Comment by tbetcke** [comment]
Hi, I have been asking myself the same question. We are trying to get rsmpi to work in a Cray environment and have run into a couple of issues. If we could organise for the project to continue this would be great. Right now, we are doinng our local patches, which obviously is not ideal.

**Comment by bsteinb** [comment]
Hi, glad to hear there is someone using the project! Speaking for myself, yes interest in this project has certainly waned since I started working on it six years ago. Many things have changed. I have two kids now. I no longer work with MPI on a daily basis.

On top of that, the initial rush of accomplishing something at some point was quenched by doubt about whether the work done so far has any value (see the many open issues about things that need to be improved w.r.t. safety).

I am not opposed to giving people access to take the project forward as I have done with @AndrewGaspar in the past. Let me know if you are interested.

**Comment by tbetcke** [comment]
Hi, first of all thanks for all your great work on the project. I don't have enough MPI expertise or resources to take ownership of this project. Together with @skailasa I am currently working on a Rust library that uses MPI. We are targeting Cray and Fujitsy ARM clusters. On our local workstations everything runs fine with rsmpi. But we ran into issues with the Cray MPI implementation.

@skailasa and I discussed today what to do about rsmpi as it seems non-active.

Options for us are:

- Factor out mpi-sys and put into a separate repository together with our patches
- Write a small shim library just with our required functions that directly calls into the Cray MPI

We would love to use the whole of rsmpi. But we simply do not have the resources alone to maintain it and have run into some locking bugs on Cray that appear in rsmpi, but not in the low-level mpi-sys bindings.

I have put in an application at my university to get software engineering resources for Rust HPC development. But this may still take a little while to be decided. If successful we may have enough power to take on mpi-sys, though probably not the whole of rsmpi.

If we can get others together to have a group of people to maintain all of rsmpi, this would be great. rsmpi is an amazing project and could become an important part of the growing Rust HPC ecosystem. But if just a single person takes it on without the knowledge/resources to push it on, it will wither again.

Would love to hear your opinion (and others) on the best way forward.

**Comment by skailasa** [comment]
Hi @bsteinb, I'd like to say thank again for such a great project, which has been really useful for us as we transition to attempting HPC in rust.

From a usage perspective, I think @tbetcke has enacsulated our main hurdles in his comment, it would be great to get a check on how many other people are attempting HPC in rust and are using this crate actively, perhaps we could establish a discord, as so much hard work has gone into this project already.

**Comment by zolkko** [comment]
Our project depends on this crate. We are running a computation (mpich2) on our small Xeon Beowulf cluster. And, to be honest, currently, the library provides me with everything I need.

But I would not mind if you publish an updated version to crates.io. ;]

**Comment by skailasa** [comment]
@zolkko, what kind of MPI functionality do your projects require at the moment? Are you just using basic mpi primitives? Or more complex features?

**Comment by jedbrown** [comment]
Thanks again for starting this project. (And hi, @tbetcke :wave:, it's good to see you're pursuing this as well.) We're using rsmpi in [petsc-rs](https://gitlab.com/petsc/petsc-rs), which was created as a summer project by @zackjorquera and our group (especially @jeremylt) continues to develop. We also develop [libceed](https://lib.rs/crates/libceed) and are prototyping Rust at the application level (parallel PDE solvers). Although we don't have dedicated funding for Rust-HPC at this time, I think we have enough relevant MPI and Rust expertise to help with maintaining this library.

Judging from the open issues and PR dialog, I think recent release planning has been too ambitious and it makes sense to postpone complicated improvements that have stalled (e.g., #79) rather than block releases on them. In particular, many projects currently use rsmpi from Git because the latest release is almost four years and and doesn't work. This blocks all such projects from releasing on crates.io, which I think is more unhealthy for this sort of project than a bit of interface churn.

**Comment by tbetcke** [comment]
Hi @jedbrown, great that you are interested in this. We have strong interest in contributing to this library, @skailasa has done some patches to compile RSMPI on EPSRC's Archer2 platform (Cray). Right now we maintain this separately. But that is obviously not sustainable. The question is how to take the leadership of the project forward and how to organise around this. @jedbrown would it make sense to have a separate call to discuss Rust/MPI and how to take forward?

**Comment by tbetcke** [comment]
@jedbrown I can do 4:10. Can you send me a Teams or Zoom invite?

**Comment by skailasa** [comment]
> Sent. (Anyone else following this issue, just ping if you'd like to join.)

Hi @jedbrown , can you add me to the call please!
