### ISSUE TITLE
State of crate

### ISSUE THREAD

**Issue by SebastianJL** [rsmpi/rsmpi#120]
Hi everyone

I just wanted to ask about the state of the crate. I am considering doing a master thesis on the topic of high performance computing in rust.
I didn't yet look at the crate a lot and haven't tried it out yet. But I thought I'd still ask.

- How active is development?
- Are there major features missing in order to use it for scientific purposes?

I might answer these questions myself at some point, but if you have something to say about it I would love to hear it.

**Comment by adamreichold** [comment]
> How active is development?

It is still moving but very very slowly due to lack of time available to the maintainers. Personally, I am also not using MPI in current my day job so the priority of working on the crate is limited for me.

> Are there major features missing in order to use it for scientific purposes?

I think it is usable, at the least the main branch which has updated dependencies and build fixes.

From my POV, the main aim of development was soundness fixes which acknowledge that data received via MPI needs verification before putting it into typed variables in general. The main problem here is doing this in a way that acknowledges that there is implicit trust between the communicating processes most environments where MPI is used, i.e. so that escape hatches are provided that unsafely bypass verification with a minimum amount of effort. Think of writing

```rust
// SAFETY: We only run this on our HPC cluster in a controlled environment.
let data = unsafe { received_data.assume_init() };
```

**Comment by SebastianJL** [comment]
Thanks for the detailed answer. I'll come back to you if I have more questions :)

**Comment by jedbrown** [comment]
With the [0.6 release](https://github.com/rsmpi/rsmpi/releases/tag/mpi-0.6.0), I'll close this issue, but feel free to follow up with further questions.
