### ISSUE TITLE
Should ready send be unsafe?

### ISSUE THREAD

**Issue by jedbrown** [rsmpi/rsmpi#182]
Ready send is quite unsafe, as I've documented in https://github.com/rsmpi/rsmpi/commit/1e5eeabc7f2b7f55976d3bc8df0867a229d03425 after someone accidentally misused it. @jtronge @hppritcha :wave: Do you feel like there is any way to make a safe ready send (and would that be worth it)? My biggest concern here is that while misuse can often be reported by MPI, it is not even deterministically knowable whether the a receive has been posted before a ready send is initiated. I think there are some symbolic execution/formal methods techniques that can be applied to this problem, but I don't see a way to get that sort of thing into the Rust type system. Also, I think ready-send is quite a niche that we shouldn't be encouraging users to use. Shall I make the ready send interfaces `unsafe` for mpi-0.8?

**Comment by jtronge** [comment]
I agree, I think these should be made unsafe. @hppritcha mentioned that some mpi p2p code could fail the send call if a matching receive hasn't been posted yet, but this doesn't seem to be a guarantee since the standard says this case is UB (mpi 4.0, section 3.4): "A send that uses the ready communication mode may be started only if the matching receive is already posted. *Otherwise, the operation is erroneous and its outcome is undefined*."

I don't think there's a way to do this ourselves in RSMPI without losing the possible performance benefit of a ready send. It would probably need to be done at a lower-level.

**Comment by jedbrown** [comment]
Thanks! Yeah, so it would be possible to decouple the unsafety by having a ZST token (or "proof") obtainable in various ways (a logical collective that could be a synchronizing collective assert) that must be submitted to the ready send. So you could get the token safely by actually doing the collective (or other sequencing operation) and could get it unsafely by what is essentially an assertion (easier for a human to check, and perhaps possible to check programmatically if one of the verifiers (like prusti, creusot, and flux) gains some parallel features. I agree that getting the token safely (via an actual collective) usually defeats any performance benefit. Proving correctness of such things sounds like a research project.

When I mark the current methods `unsafe`, should I use names like `immediate_ready_send_unchecked` to keep the unqualified namespace available in case such a research project succeeds in making a safer pattern? Given that there would need to be this token, those methods might have qualified names like `immediate_ready_send_with_token` anyway.
