### ISSUE TITLE
docs.rs failed to build the docs

### ISSUE THREAD

**Issue by gnzlbg** [rsmpi/rsmpi#61]
E.g. see here for the error log: https://docs.rs/crate/mpi-sys/0.1.2/builds/122941

`docs.rs` is very configurable, supports building the docs for different, user-defined targets, etc. 

If there is anything special that you need to build the docs there it might be worth it to open an issue on docs.rs now that it has been moved to the rust-lang organization and get it sorted out :) 

Let me know if I can help!

**Comment by bsteinb** [comment]
`mpi-sys` depends on a native MPI library and currently is not capable of installing one by itself if it does not find one on the system.

It seems that the folks at `docs.rs` are open to installing native dependencies on the build machines. I will contact them regarding installing either OpenMPI or MPICH.

**Comment by huangjj27** [comment]
In 2020, docs.rs can‘t find this crate, and the. self hosted document is also unreachable. please fix it soon!

**Comment by AndrewGaspar** [comment]
Hi, sorry, the docs are here now: http://rsmpi.github.io/rsmpi/mpi/index.html

Unfortunately, we haven't cut a release since moving to the new org.

@bsteinb Could you add me as an owner on crates.io and I could start looking it cutting a new release?

**Comment by bsteinb** [comment]
@AndrewGaspar invites should be in your inbox.

I have set up Travis CI to be able to deploy new releases (i.e. to crates.io, GitHub releases, and documentation on github.io) when a new tag is pushed (just name the tags `mpi-X.Y.Z`, `mpi-sys-X.Y.Z` `build-probe-mpi-X.Y.Z`). Some of that might be broken by now. I remember having problems in the past after not doing a release for some time, because deploy tokens get revoked if they go unused.

**Comment by bsteinb** [comment]
I am taking a stab at adding an MPI library to the docs.rs build environment.

**Comment by bsteinb** [comment]
Pull request is here https://github.com/rust-lang/crates-build-env/pull/53

**Comment by jedbrown** [comment]
We are now published on docs.rs: https://docs.rs/mpi/latest/mpi/

Should we update official docs to point there instead of the self-hosted page?
